export const cityCountry = {
    "Madrid": "España",
    "Barcelona": "España",
    "Valencia": "España",
    "Sevilla": "España",
    "Zaragoza": "España",
    "Málaga": "España",
    "Murcia": "España",
    "Palma": "España",
    "Las Palmas": "España",
    "Bilbao": "España",
    "Alicante": "España",
    "Córdoba": "España",
    "Valladolid": "España",
    "Vigo": "España",
    "Gijón": "España",
    "Hospitalet de Llobregat": "España",
    "Vitoria-Gasteiz": "España",
    "La Coruña": "España",
    "Granada": "España",
    "Elche": "España",
    "Oviedo": "España",
    "Badalona": "España",
    "Cartagena": "España",
    "Terrassa": "España",
    "Jerez de la Frontera": "España",
    "Sabadell": "España",
    "Móstoles": "España",
    "Santa Cruz de Tenerife": "España",
    "Pamplona": "España",
    "Almería": "España",
    "Alcalá de Henares": "España",
    "Fuenlabrada": "España",
    "Leganés": "España",
    "San Sebastián": "España",
    "Getafe": "España",
    "Burgos": "España",
    "Santander": "España",
    "Albacete": "España",
    "Castellón de la Plana": "España",
    "Alcorcón": "España",
    "San Cristóbal de La Laguna": "España",
    "Logroño": "España",
    "Badajoz": "España",
    "Salamanca": "España",
    "Huelva": "España",
    "Marbella": "España",
    "Lérida": "España",
    "Tarragona": "España",
    "León": "España",
    "Cádiz": "España",
    "Jaén": "España",
    "Ourense": "España",
    "Lugo": "España",
    "Santiago de Compostela": "España",
    "Cáceres": "España",
    "Melilla": "España",
    "Ceuta": "España"
  };


