name: Run Tests

on:
  push:
    branches:
      - main # Run tests on pushes to the main branch
  pull_request:
    branches:
      - main # Run tests on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the Node.js version you are using

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
